apiVersion: v1
kind: Pod
metadata:
  name: nats-ops-custom-15
spec:
  serviceAccountName: example-nats-user 
  restartPolicy: Never
  containers:
    - name: nats-ops
      # command: ["echo", "'okookokokokokok'", "&&", "sleep", "300"]
      command: ["/bin/sh"]
      image: "wallyqs/nats-ops:latest"
      # image: "busybox:latest"
      tty: true
      stdin: true
      stdinOnce: true
